---
# tasks file for psql_HA
- name: Debug Inventory Host Tags
  debug:
    var: hostvars[inventory_hostname].tags['Name']

- name: RepMgr | packages
  import_tasks: RepMgr.yml

- name: Master | Replication setup
  import_tasks: Master.yml
  when: hostvars[inventory_hostname].tags['Name'] == 'PG-SQL-master'

- name: Standby.yml | Replication setup
  import_tasks: Standby.yml
  when: hostvars[inventory_hostname].tags['Name'] == 'PG-SQL-Slave-1' or hostvars[inventory_hostname].tags['Name'] == 'PG-SQL-Slave-2'

- name: Run Daemon
  include_tasks: Daemon.yml

# - name: Rejoin Nodes
#   import_tasks: failover-rejoin.yml
#   when: hostvars[inventory_hostname].tags['Name'] == 'PG-SQL-master' or hostvars[inventory_hostname].tags['Name'] == 'PG-SQL-Slave-2'
...
