---
# Variable setup.
- name: Include OS-Specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Include RedHat tasks
  ansible.builtin.include_tasks:
    file: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian tasks
  ansible.builtin.include_tasks:
    file: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include User tasks
  ansible.builtin.include_tasks:
    file: users.yml
  when: postgresql_users

- name: Include Database tasks
  ansible.builtin.include_tasks:
    file: database.yml
  when: postgresql_database
