---
- name: Install Gpg
  apt:
    name: gnupg
    state: present

- name: Add PostgreSQL APT repository key
  apt_key:
    url: "{{ postgresql_repo_key_url }}"
    state: present

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "{{ postgresql_repo_url }}"
    state: present

- name: Install PostgreSQL on Ubuntu
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ debian_package }}"

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true

- name: Configure PostgreSQL
  template:
    src: ubuntu_postgresql.j2
    dest: /etc/postgresql/{{ version }}/main/postgresql.conf

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

