---

- name: Install Gpg
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add PostgreSQL APT repository key
  ansible.builtin.apt_key:
    url: "{{ postgresql_repo_key_url }}"
    state: present

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "{{ postgresql_repo_url }}"
    state: present

- name: Install PostgreSQL on Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ debian_package }}"

- name: Start PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Configure PostgreSQL
  ansible.builtin.template:
    src: ubuntu_postgresql.j2
    dest: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    mode: "0644"

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true
