---
- name: Create a user in the database
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    encrypted: true
  loop: "{{ user_list }}"
